# Generated by Django 4.2.7 on 2026-04-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Reporting Manager',
                'verbose_name_plural': 'Reporting Managers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VPIndia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'VP India',
                'verbose_name_plural': 'VP India',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.team'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vp_india',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
