# Generated by Django 4.2.7 on 2026-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options_employee_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('', 'None'), ('Active', 'Active'), ('Exited', 'Exited')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('', 'None'), ('Full Time', 'Full Time'), ('Intern', 'Intern'), ('Contract', 'Contract')], max_length=20),
        ),
    ]
