# Generated by Django 4.2.7 on 2026-04-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_status_alter_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='experience_prior_adf',
            field=models.CharField(help_text='Years of experience', max_length=10),
        ),
    ]
