# Generated by Django 4.2.7 on 2026-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_update_experience_to_char_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exit_reason',
            field=models.TextField(blank=True, help_text='Reason for exit (max 250 characters)', max_length=250, null=True),
        ),
    ]
