# Generated by Django 4.2.7 on 2026-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_exit_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idle_timeout_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Idle timeout in minutes before auto-logout'),
        ),
    ]
