# Generated by Django 4.2.7 on 2026-05-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_user_idle_timeout_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idle_timeout_minutes',
        ),
    ]
